theme: jekyll-theme-minimal
title: Julia Christin Prein
logo: https://github.com/jprein/personal/blob/a5b775cf41e6342353e676c38e7115fca8ac76f3/profil_small.png?raw=true
description: Add description here
